# This is a basic workflow to help you get started with Actions

name: AndroidTest

# Controls when the action will run. 
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
